devices:
- input_name: 'Contour Design ShuttleXpress'
  input_phys: 'usb-0000:01:00.0-1.1/input0'
  output_name: remap-shuttle
  remappings:
    BTN_4:
    - modifier_group: modA
    BTN_5:
    - modifier_group: modX
    BTN_6:
    - modifier_group: modY
    BTN_7:
    - modifier_group: modZ
    BTN_8:
    - code: SOCKET
      host: "http://127.0.0.1:8000"
      command: "homing"



  modifier_groups:
    modA:
      REL_DIAL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 A"]
        speed: 120
      REL_WHEEL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 A"]
        speed: 10
        rate: 0.01
    modX:
      REL_DIAL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 X"]
        speed: 2000
      REL_WHEEL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 A"]
        speed: 500 #options are 1 - keydown, 0 - keyup, 2- both keydown and up
        rate: 0.01
    modY:
      REL_DIAL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 Y"]
        speed: 2000
      REL_WHEEL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 A"]
        speed: 500 #options are 1 - keydown, 0 - keyup, 2- both keydown and up
        rate: 0.01
    modZ:
      REL_DIAL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 Z"]
        speed: 2000
      REL_WHEEL:
      - code: SOCKET
        host: "http://127.0.0.1:8000"
        command: ["gcode", "G91 G1 A"]
        speed: 500 #options are 1 - keydown, 0 - keyup, 2- both keydown and up
        rate: 0.01






















